[versions]
restate = '2.2.0'
jackson = '2.18.1'
junit = '5.11.3'
log4j = '2.24.1'
kotlinx-coroutines = '1.8.1'
kotlinx-serialiation = '1.7.3'

[libraries]
restate-sdk-api = { module = "dev.restate:sdk-api", version.ref = "restate" }
restate-sdk-api-gen = { module = "dev.restate:sdk-api-gen", version.ref = "restate" }
restate-sdk-api-kotlin = { module = "dev.restate:sdk-api-kotlin", version.ref = "restate" }
restate-sdk-api-kotlin-gen = { module = "dev.restate:sdk-api-kotlin-gen", version.ref = "restate" }
restate-sdk-common = { module = "dev.restate:sdk-common", version.ref = "restate" }
restate-sdk-http-vertx = { module = "dev.restate:sdk-http-vertx", version.ref = "restate" }
restate-sdk-request-identity = { module = "dev.restate:sdk-request-identity", version.ref = "restate" }
restate-sdk-lambda = { module = "dev.restate:sdk-lambda", version.ref = "restate" }
restate-sdk-serde-jackson = { module = "dev.restate:sdk-serde-jackson", version.ref = "restate" }
restate-sdk-testing = { module = "dev.restate:sdk-testing", version.ref = "restate" }
restate-client = { module = "dev.restate:client", version.ref = "restate" }
restate-client-kotlin = { module = "dev.restate:client-kotlin", version.ref = "restate" }

jackson-parameter-names = { module = "com.fasterxml.jackson.module:jackson-module-parameter-names", version.ref = "jackson" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }

log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialiation" }